# Generated by Django 4.2.5 on 2023-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_candidato', models.PositiveIntegerField()),
                ('votos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muni', models.CharField(max_length=100)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vqr', models.FloatField()),
                ('vrch', models.CharField(max_length=100)),
                ('orig', models.CharField(max_length=100)),
                ('orlc', models.CharField(max_length=100)),
                ('proc', models.CharField(max_length=100)),
                ('dtpl', models.CharField(max_length=100)),
                ('plei', models.CharField(max_length=100)),
                ('turn', models.CharField(max_length=100)),
                ('fase', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('seca', models.CharField(max_length=100)),
                ('idue', models.CharField(max_length=100)),
                ('idca', models.CharField(max_length=100)),
                ('loca', models.CharField(max_length=100)),
                ('apto', models.PositiveIntegerField()),
                ('comp', models.PositiveIntegerField()),
                ('falt', models.PositiveIntegerField()),
                ('datab', models.CharField(max_length=100)),
                ('hrab', models.CharField(max_length=100)),
                ('dtfc', models.CharField(max_length=100)),
                ('hrfc', models.CharField(max_length=100)),
                ('idel', models.CharField(max_length=100)),
                ('carg', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('verc', models.CharField(max_length=100)),
                ('apta', models.PositiveIntegerField()),
                ('nomi', models.PositiveIntegerField()),
                ('bran', models.PositiveIntegerField()),
                ('nulo', models.PositiveIntegerField()),
                ('totc', models.PositiveIntegerField()),
                ('hash', models.TextField()),
                ('assi', models.TextField()),
                ('candidato', models.ManyToManyField(to='eleicao.candidatos')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unfe', models.CharField(max_length=100)),
                ('cidade', models.ManyToManyField(to='eleicao.cidades')),
            ],
        ),
        migrations.AddField(
            model_name='cidades',
            name='urna',
            field=models.ManyToManyField(to='eleicao.urnas'),
        ),
    ]
