# Generated by Django 4.2.5 on 2023-09-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_candidato', models.PositiveIntegerField()),
                ('votos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muni', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vqr', models.FloatField()),
                ('vrch', models.IntegerField()),
                ('orig', models.CharField(max_length=100)),
                ('orlc', models.CharField(max_length=100)),
                ('proc', models.IntegerField()),
                ('dtpl', models.IntegerField()),
                ('plei', models.IntegerField()),
                ('turn', models.IntegerField()),
                ('fase', models.CharField(max_length=100)),
                ('zona', models.IntegerField()),
                ('seca', models.IntegerField()),
                ('idue', models.IntegerField()),
                ('idca', models.IntegerField()),
                ('loca', models.IntegerField()),
                ('apto', models.IntegerField()),
                ('comp', models.IntegerField()),
                ('falt', models.IntegerField()),
                ('datab', models.IntegerField()),
                ('hrab', models.IntegerField()),
                ('dtfc', models.IntegerField()),
                ('hrfc', models.IntegerField()),
                ('idel', models.IntegerField()),
                ('carg', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('verc', models.IntegerField()),
                ('apta', models.IntegerField()),
                ('nomi', models.IntegerField()),
                ('bran', models.IntegerField()),
                ('nulo', models.IntegerField()),
                ('totc', models.IntegerField()),
                ('hash', models.TextField()),
                ('assi', models.TextField()),
                ('candidato', models.ManyToManyField(to='eleicao.candidatos')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unfe', models.CharField(max_length=100)),
                ('cidade', models.ManyToManyField(to='eleicao.cidades')),
            ],
        ),
        migrations.AddField(
            model_name='cidades',
            name='cidade',
            field=models.ManyToManyField(to='eleicao.urnas'),
        ),
    ]
