# Generated by Django 4.2.5 on 2023-09-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidades',
            old_name='cidade',
            new_name='urna',
        ),
        migrations.AlterField(
            model_name='cidades',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
