# Generated by Django 4.2.5 on 2023-09-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0002_processoeleitoral_urnas_processo_eleitoral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatos',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='cidades',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='processoeleitoral',
            options={'verbose_name': 'Processo Eleitoral', 'verbose_name_plural': 'Processos Eleitorais'},
        ),
        migrations.AlterModelOptions(
            name='urnas',
            options={'verbose_name': 'Urna', 'verbose_name_plural': 'Urnas'},
        ),
    ]
