# Generated by Django 4.2.5 on 2023-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_alter_candidatos_options_alter_cidades_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urnas',
            name='apta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='apto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='bran',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='comp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='falt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='nomi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='nulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='totc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urnas',
            name='vqr',
            field=models.CharField(max_length=100),
        ),
    ]
